### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by Axdr3w** [pybricks/support#1239]
Traceback (most recent call last):
  File "mission_01_cinema.py", line 8, in <module>
NameError: name 'Motor' isn't defined
WHAT. THE. HELL???
Traceback (most recent call last):
  File "mission_01_cinema.py", line 8, in <module>
NameError: name 'Motor' isn't defined

Traceback (most recent call last):
  File "mission_01_cinema.py", line 8, in <module>
NameError: name 'Motor' isn't defined

**Comment by laurensvalk** [comment]
What does the code look like that produces this error?

Maybe Motor wasn’t imported?
