### ISSUE TITLE
[Bug] Failed to install Pybricks Firmware on TechnicHub 88012 

### ISSUE THREAD

**Issue by yolgs** [pybricks/support#1245]
**Describe the bug**
Error message when trying to install firmware on Lego TechnicHub 88012 when using Pybricks (v3.2.3  - Pybricks Code v2.1.1).
Browser: Edge.

**To reproduce**
1. Open Edge
2. Go to Pybricks
3. Click on Install Firmware
4. Select Lego TechnicHUb 88012
5. Press button on Hub until it blinks purple
6. Click on Install
7. Pair with LegoBootloader
--> then installation / Pairing window disappears and error message see below pops up.

**Expected behavior**
Firmware installed and hub ready to be run from Pybricks

ErrorMessage in Pybricks:

```
Error: Failed to execute 'getPrimaryService' on 'BluetoothRemoteGATTServer': GATT Server is disconnected. Cannot retrieve services. (Re)connect first with `device.gatt.connect`.
    at P.<computed> (https://code.pybricks.com/static/js/main.a3e3d8b4.js:2:1479169)
    at https://code.pybricks.com/static/js/main.a3e3d8b4.js:2:1483081
    at m (https://code.pybricks.com/static/js/main.a3e3d8b4.js:2:1484027)
    at h (https://code.pybricks.com/static/js/main.a3e3d8b4.js:2:1483538)
    at u (https://code.pybricks.com/static/js/main.a3e3d8b4.js:2:1483810)
```

**Comment by dlech** [comment]
We've had a number of people report this issue. You can review the similar issues with [this search](https://github.com/search?q=repo%3Apybricks%2Fsupport+GATT+Server+is+disconnected.+Cannot+retrieve+services.&type=issues).

I think for some people, using a different Bluetooth adapter made a difference (but I might be confusing that with a different issue).

Also be sure to check out the tips at https://github.com/orgs/pybricks/discussions/270 to make sure it is not something easy like disconnecting all other Bluetooth devices or having a low battery.
