### ISSUE TITLE
[Bug] Read the docs builds are broken

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#1536]
**Describe the bug**
`rtd` no longer has toml out of the box, it seems.

```
Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pybricks-api/envs/work/lib/python3.10/site-packages/sphinx/config.py", line 358, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/docs/checkouts/readthedocs.org/user_builds/pybricks-api/checkouts/work/doc/main/conf.py", line 48, in <module>
    exec(open(os.path.abspath("../common/conf.py")).read())
  File "<string>", line 33, in <module>
ModuleNotFoundError: No module named 'toml'
```

**Comment by laurensvalk** [comment]
Rather than that, it's not using our venv:

![image](https://github.com/pybricks/support/assets/12326241/8d508d1e-00b2-4f53-954b-c83b48eeface)

**Comment by laurensvalk** [comment]
Fixed in https://github.com/pybricks/pybricks-api/commit/32a63a4c09292ece63622600da6c3bbf837ebb57 via https://github.com/python-poetry/poetry/issues/9025
