### ISSUE TITLE
[Bug] Custom python modules (directories) don't get compiled onto the hub. 

### ISSUE THREAD

**Issue by TomJuri** [pybricks/support#1602]
**Describe the bug**
Custom python modules (folders) don't get compiled onto the hub. Everything works fine when I put every python file that gets imported by any other python file into the project root. However, when I try to import a file that's within a directory, this error occurs:
```
[tom@neon:~/Coding/2425-RobotCode]$ pybricksdev run ble main.py 
Searching for any hub with Pybricks service...
Traceback (most recent call last):
  File "/home/tom/Coding/2425-RobotCode/venv/bin/pybricksdev", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/tom/Coding/2425-RobotCode/venv/lib/python3.11/site-packages/pybricksdev/cli/__init__.py", line 383, in main
    asyncio.run(subparsers.choices[args.tool].tool.run(args))
  File "/home/tom/.nix-profile/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/tom/.nix-profile/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/.nix-profile/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/tom/Coding/2425-RobotCode/venv/lib/python3.11/site-packages/pybricksdev/cli/__init__.py", line 207, in run
    await hub.run(script_path, args.wait)
  File "/home/tom/Coding/2425-RobotCode/venv/lib/python3.11/site-packages/pybricksdev/connections/pybricks.py", line 572, in run
    mpy = await compile_multi_file(py_path, abi)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/Coding/2425-RobotCode/venv/lib/python3.11/site-packages/pybricksdev/compile.py", line 119, in compile_multi_file
    finder.run_script(path)
  File "/home/tom/.nix-profile/lib/python3.11/modulefinder.py", line 153, in run_script
    self.load_module('__main__', fp, pathname, stuff)
  File "/home/tom/.nix-profile/lib/python3.11/modulefinder.py", line 349, in load_module
    self.scan_code(co, m)
  File "/home/tom/.nix-profile/lib/python3.11/modulefinder.py", line 411, in scan_code
    self._safe_import_hook(name, m, fromlist, level=0)
  File "/home/tom/.nix-profile/lib/python3.11/modulefinder.py", line 367, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/home/tom/.nix-profile/lib/python3.11/modulefinder.py", line 165, in import_hook
    q, tail = self.find_head_package(parent, name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/.nix-profile/lib/python3.11/modulefinder.py", line 221, in find_head_package
    q = self.import_module(head, qname, parent)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/.nix-profile/lib/python3.11/modulefinder.py", line 308, in import_module
    fp, pathname, stuff = self.find_module(partname,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/.nix-profile/lib/python3.11/modulefinder.py", line 489, in find_module
    return _find_module(name, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/.nix-profile/lib/python3.11/modulefinder.py", line 69, in _find_module
    if spec.loader.is_package(name):
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'is_package'
```

When I add an __init__.py file to the directory, it successfully uploads the file to the hub but fails importing it:
```
[tom@neon:~/Coding/2425-RobotCode]$ pybricksdev run ble main.py 
Searching for any hub with Pybricks service...
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 316/316 [00:00<00:00, 2.14kB/s]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
ImportError: can't import name actual_module
```

However, when I remove the actual_module file and put the functions into the __init__.py file and remove the actual_module part from the import statement, everything works fine (except for my IDE not picking up the function)

**To reproduce**
1. Create a pybricks project
2. Create main file
3. Create module
4. Import module in main

**Expected behavior**
It compiles every single file successfully, and it runs without any issues.

**Screenshots**
![image](https://github.com/pybricks/support/assets/99533320/5c0f848c-3574-442d-bf00-08c4e321dc83)

I hope my explanation of this issue was sufficient, and thanks in advance!

**Comment by dlech** [comment]
Can you share you `main.py`?

**Comment by TomJuri** [comment]
```
from my_module import actual_module

actual_module.my_func()
```

**Comment by laurensvalk** [comment]
> Everything works fine when I put every python file that gets imported by any other python file into the project root.

This is currently the only officially supported way.

> Custom python modules (folders) don't get compiled onto the hub. 

If this doesn't require firmware changes, I think we could consider supporting this in Pybricksdev.

**Comment by TomJuri** [comment]
A possible workaround might be parsing all the python files and moving them to the project root and then obviously changing the imports in a script, however it would be quite nice if pybricksdev would support this natively. Looking forward to what you figure out!

**Comment by laurensvalk** [comment]
I seem to recall this was working at some point.

I think support for this was removed in: https://github.com/pybricks/pybricksdev/commit/ff328265f736f9a8e81ec15ff2f6e13065c894da

"This also removes support for relative imports since Python doesn't support them outside of packages."

**Comment by laurensvalk** [comment]
Just hacking around with Pybricksdev a bit to put some of https://github.com/pybricks/pybricksdev/commit/ff328265f736f9a8e81ec15ff2f6e13065c894da back in, it appears that the firmware still works for the following use case (see folder structure on the left).

![image](https://github.com/pybricks/support/assets/12326241/dc981b73-16fc-4dfb-9310-fb51ab94aa3d)

https://github.com/pybricks/pybricksdev/commit/ff328265f736f9a8e81ec15ff2f6e13065c894da was probably done for good reason (as it does make the code cleaner), but maybe there's a way to achieve the same with the `ModuleFinder` introduced there.

**Comment by TomJuri** [comment]
Seems like this would just work without any modifications required if this bug in python got fixed. https://github.com/python/cpython/issues/84530

**Comment by dlech** [comment]
Recapping, there are two "bugs" here, one in the CPython standard library and one is a firmware limitation.

1. Not being able to find imports when there is an implicit namespace package
   - This is https://github.com/python/cpython/issues/84530
   - Workaround is to include `__init__.py` so there isn't an implicit namespace package
2. The following code fails in Pybricks MicroPython
    ```python
    from my_module import actual_module

    actual_module.my_func()
    ```

     with `ImportError: can't import name actual_module`

    - The module is actually found and compiled into the `.mpy` file like it is supposed to be.
    - This is probably a limitation of how we implemented imports in the firmware.
    - Workaround is to write the code like this instead:
    ```python
    from my_module.actual_module import my_func

    my_func()
    ```

**Comment by LeanderGlanda** [comment]
I'm affected by this bug too. It would be really nice to be able to have submodules so I could structure code better.

I don't fully get what's wrong. 
So there is a bug in CPython, which makes that me need the init.py in a submodule/folder, right?
And the other bug is in the pybricks firmware or in pybricksdev?

**Comment by joeyparrish** [comment]
How about an argument to pybricksdev to specify an additional module to explicitly include?

For example,

```sh
pybricksdev run --include pybricksmenu ble main.py
```

That would find `pybricksmenu` and explicitly include it.  Experimentally, I find that this hack in `compile.py` works:

```py
    # ADD THIS:
    for module_name in additional_modules:
        finder.modules[module_name] = importlib.import_module(module_name)

    # THIS IS ORIGINAL:
    for name, module in finder.modules.items():
```

Populating this `additional_modules` list from command line arguments for the `compile` and `run` tools would be incredibly useful for sharing utility code between projects.

Would something like this be an acceptable PR?  Happy to contribute.

**Comment by dlech** [comment]
I'm not opposed to adding something like that. Although I would suggest implementing it slightly differently. There are two approaches I would consider (and are not mutually exclusive).

1 . We could add something similar to the `PYTHONPATH` environment variable in Python that adds extra search paths to use when using the existing automagical import includer. I think a command line option would be easier to use than an environment variable though.
2. Have an option to explicitly only include the specified files. This option would need to be specified multiple times to include multiple files. In this case the automagical search would be skipped and only the files given on the command line would be compiled and downloaded. This would enable scenarios like:

  ```python
  try:
      import my_module_a as my_module
  except ImportError:
      import my_module_b as my_module
  ```

   Then you could `pybricksdev run ble main.py --include-only my_module_a.py` or `pybricksdev run ble main.py --include-only my_module_b.py` to run the same program with different sets of parameters.

Or maybe you have some use case with dynamic imports where we would want both the autmagical includes and some extra includes?

Or is this just about not having all of the files in the same directory?

**Comment by laurensvalk** [comment]
To clarify, submodules and package structures are already working. Everything is automatically included. For example:

<img width="361" height="292" alt="Image" src="https://github.com/user-attachments/assets/a9a97a62-e393-4567-afe4-8f94cc6f6735" />

<img width="1483" height="1200" alt="Image" src="https://github.com/user-attachments/assets/4f1a3919-42f0-4970-a53d-1d0318155b63" />

The only limitation is that you must do:

```python

from more.evenmore.last import data

print(data)

```

instead of 


```python
from more.evenmore import last

# Doesn't work
print(last.data)
```

But that can't be so bad?

**Comment by joeyparrish** [comment]
> To clarify, submodules and package structures are already working. Everything is automatically included.  ... But that can't be so bad?

I'm motivated to have a module that contains code that shouldn't be in the same repo.  The main.py that runs on the robot is importing a library of utility code.  Modules are only working today if you're willing to put everything in the same place.  That's the limitation I'm frustrated by today.


> 1. We could add something similar to the PYTHONPATH environment variable in Python that adds extra search paths to use when using the existing automagical import includer. I think a command line option would be easier to use than an environment variable though.

I tried something along these lines locally, but I was unable to figure out how to make modulefinder happy with the paths I was providing.  (e.g. /usr/local/lib/python3.12/dist-packages)


> 2. Have an option to explicitly only include the specified files. This option would need to be specified multiple times to include multiple files. In this case the automagical search would be skipped and only the files given on the command line would be compiled and downloaded.

This would be perfect for me.  From my experiments (see above), this works well.  I didn't plumb it all the way through the command line yet because I wanted to check with maintainers first on my approach.  If/when there's a consensus around this, I'm happy to implement it.

**Comment by dlech** [comment]
> but I was unable to figure out how to make modulefinder happy with the paths I was providing. (e.g. /usr/local/lib/python3.12/dist-packages)

That path sounds a bit suspicious since we should be searching for MicroPython modules rather than Python modules. 😄 


> If/when there's a consensus around this, I'm happy to implement it.

I would still lean towards the extra search paths since that is more like what people might already be familiar with from Python and it would be less verbose if you were using a bunch of modules from a single library.
