### ISSUE TITLE
[Bug] "Internal Error"

### ISSUE THREAD

**Issue by AW737** [pybricks/support#1705]
Q: What is the problem?
A: When I open the page to the code (code.pybricks.com), it just shows an error message at the top, and 
after a second, the webpage just flashes to a white screen.

1. Go to 'code.pybricks.com'
2. See error

What did you expect to happen instead?
To open the page to let me code

There is a saying that a picture is worth a 1000 words. Screenshots really help to identify and solve problems.
So, it's pretty hard to take a screenshot of it since I have a small window of taking it, so here's some of the page and the error message. After I see that, it just flashes to white, until I reload the page, which the same thing happens.

![Screenshot 2024-07-08 9 48 56 AM](https://github.com/pybricks/support/assets/173724838/3d81cfa3-578c-4b53-8c32-2d1935e99da6)

Don't know if I should put the error message here but, hey it's my first time.
```
UnknownError: Internal error.
 UnknownError: Internal error.
    at De.rejectionMapper (https://code.pybricks.com/static/js/main.1bf60dfd.js:2:1595134)
    at je (https://code.pybricks.com/static/js/main.1bf60dfd.js:2:1529120)
    at IDBOpenDBRequest.<anonymous> (https://code.pybricks.com/static/js/main.1bf60dfd.js:2:1556385)
    at IDBOpenDBRequest.<anonymous> (https://code.pybricks.com/static/js/main.1bf60dfd.js:2:1530914)
```

**Comment by dlech** [comment]
What browser and version and operating system are you using?

**Comment by dlech** [comment]
https://stackoverflow.com/questions/74207049/internal-error-opening-backing-store-for-indexeddb-open

suggests restarting the computer and making sure you aren't running the browser in "private" mode.

But basically, this is a browser issue. I don't think there is anything we can do to fix it on our end.

You could also check the console log in the browser for additional errors. That could help troubleshoot the problem better.
